name: demo-com

runs:
    using: 'composite'
    steps:
    - uses: actions/checkout@v3
      if: github.repository != 'rueyaa332266/action_poc'
      with:
        repository: 'rueyaa332266/action_poc'
        ref: 'master'
    - name: check files
      run: ls .github/workflows
      shell: bash
