name: demo-com

runs:
    using: 'composite'
    steps:
    - name: Checkout when called in e2e repo
      if: github.repository == 'rueyaa332266/action_poc'
      uses: actions/checkout@v3
    - name: Checkout when called from other repo
      if: github.repository != 'rueyaa332266/action_poc'
      uses: actions/checkout@v3
      with:
        repository: 'rueyaa332266/action_poc'
        ref: 'master'
    - name: check repo
      run: echo ${{ github.repository }}
      shell: bash
    # - name: check secret
    #   run: echo ${{ secrets.CHECK }}
    #   shell: bash
    # - name: check vars
    #   run: echo ${{ vars.CHECK }}
    #   shell: bash
    - name: check files
      run: ls .github/workflows
      shell: bash
