name: com

runs:
    using: 'composite'
    steps:
      - name: Generate list using Markdown
        run: echo "line 1" >> $GITHUB_STEP_SUMMARY
        shell: bash
      - name: Generate list using Markdown
        run: |
          echo "line 2 : 123" >> $GITHUB_STEP_SUMMARY
          echo "line 3" >> $GITHUB_STEP_SUMMARY
        shell: bash
