name: demo-com

runs:
    using: 'composite'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: check repo
      run: echo ${{ github.repository }}
      shell: bash
    - name: check secret
      run: echo ${{ secrets.CHECK }}
      shell: bash
    - name: check vars
      run: echo ${{ vars.CHECK }}
      shell: bash
    - name: check files
      run: ls .github/workflows
      shell: bash
