name: sample

on: 
  workflow_dispatch:

env:
  SUMMARY_REPORT: ""

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "SUMMARY_REPORT<<EOF" >> $GITHUB_ENV
          echo "123" >> $GITHUB_ENV
          echo "456" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - run: echo ${{ env.SUMMARY_REPORT }}
  demo2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.SUMMARY_REPORT }}