name: demo-new

on:
  workflow_dispatch:
    inputs:
      input1:
        default: "test"

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      NBF: ${{ true }}
    steps:
      - name: Check input
        if: env.NBF == true
        run: echo ${{ env.NBF }}
