name: demo-new

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      input1:
        required: false
        type: boolean

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      INPUT: ${{ inputs.input1 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: check composite
        run: echo ${{ github.repository }}
