name: demo-new

on:
  workflow_dispatch:
    inputs:
      input1:
        required: false
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Check input
        env:
          check: ${{ inputs.input1 || 'something' }}
        run: echo ${{ env.check }}
