name: demo-new

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      input1:
        required: false
        type: boolean

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      INPUT: ${{ inputs.input1 }}
    steps:
      - name: Checkout when called in e2e repo
        if: github.repository == 'rueyaa332266/action_poc'
        uses: actions/checkout@v3
      - name: Checkout when called from other repo
        if: github.repository != 'rueyaa332266/action_poc'
        uses: actions/checkout@v3
        with:
          repository: 'rueyaa332266/action_poc'
          ref: 'master'
      - name: check repo
        if: (!cancelled())
        run: echo ${{ github.repository }}
      - name: check secret
        run: echo ${{ secrets.CHECK }}
      - name: check vars
        run: echo ${{ vars.CHECK }}
      - name: check files
        run: ls .github/workflows
