name: demo-new

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      input1:
        required: false
        default: false
        type: boolean

jobs:
  demo:
    runs-on: ubuntu-latest
    outputs:
      ABC: ${{ steps.set-out.outputs.ABC }}
      TEST: ${{ steps.set-out.outputs.TEST }}
    env:
      INPUT: ${{ inputs.input1 }}
    steps:
      - name: Set REPOSITORY_NAME env var
        run: ruby .github/workflows/check.rb