name: demo-new

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      input1:
        required: false
        type: boolean

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      INPUT: ${{ inputs.input1 }}
    steps:
      - name: Set REPOSITORY_NAME env var
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: fail
        continue-on-error: true
        run: exit 1
      - name: echo
        if: failure()
        run: echo failed