name: poc-1

on: 
  workflow_dispatch:

env:
  SUMMARY_REPORT: ""

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: echo '1'
  demo2:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run:  exit 2
  demo3:
    needs: [demo, demo2]
    runs-on: ubuntu-latest
    if: ${{ always() && needs.demo2.result == 'failure' }}
    steps:
      - run: echo ${{ needs.demo.result }}
      - run: echo ${{ needs.demo2.result }}