name: demo-new

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      input1:
        required: false
        type: boolean

jobs:
  demo:
    runs-on: ubuntu-latest
    outputs:
      ABC: ${{ steps.set-out.outputs.ABC }}
      TEST: ${{ steps.set-out.outputs.TEST }}
    env:
      INPUT: ${{ inputs.input1 }}
    steps:
      - name: Set REPOSITORY_NAME env var
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Set testrail to output
        id: set-out
        run: echo "ABC=123" >> "$GITHUB_OUTPUT"
  demo2:
    name: demo 2
    needs: demo
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.demo.outputs.ABC }}
      - run: echo ${{ needs.demo.outputs.TEST }}
      - run: echo ${{ needs.demo.outputs.TEST || '??' }}
      - if: needs.demo.outputs.TEST
        run: echo skip