name: poc-1

on: 
  workflow_dispatch:

env:
  SUMMARY_REPORT: ""

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: echo '1'
  demo2:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run:  echo '2'
  demo3:
    needs: [demo, demo2]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.demo.result }}