name: demo-new

on: 
  workflow_dispatch:
    inputs:
      input1:
        type: string
  workflow_call:
    inputs:
      input1:
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest
    outputs:
      ABC: ${{ steps.set-out.outputs.ABC }}
      TEST: ${{ steps.set-out.outputs.TEST }}
    env:
      INPUT: ${{ inputs.input1 }}
    steps:
      - uses: actions/checkout@v3
      - name: Set REPOSITORY_NAME env var
        run: ruby .github/workflows/check.rb
        env:
          INPUT: 123
      - run: echo {{ env.INPUT }}
