name: demo-new

on:
  workflow_call:
    inputs:
      input1:
        required: false
        type: boolean

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      INPUT: ${{ inputs.input1 || '' }}
    steps:
      - name: Check input
        run: echo ${{ env.INPUT }}
      - name: Check if
        run: ruby .github/workflows/check.rb
