name: pr-approved

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - name: 
        run: echo ${{ toJSON(github.event.review) }}
      - name: get approved count
        run: echo ${{ toJSON(github.event.pull_request) }}
      - run: echo "This PR was approved"
