name: pr-approved

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]
  schedule:
    - cron: '21 * * * *'

jobs:
  approved:
    runs-on: ubuntu-latest
    env: 
      E2E_BRANCH: main
    steps:
      - run: echo ${{ github.event.issue.number }}
      - run: echo ${{ github.event.pull_request.number }}
      - run: echo ${{ github.event.issue.number || github.event.pull_request.number }}
      - run: echo ${{ github.ref_name }}
