name: pr-approved

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  approved:
    if: ${{ startsWith(github.event.comment.body, '/e2e') || github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    env: 
      E2E_BRANCH: main
    steps:
      - run: echo ${{ github.event.issue.number }}
      - run: echo ${{ github.event.pull_request.number }}
      - run: echo ${{ github.event.issue.number || github.event.pull_request.number }}

      - uses: actions/github-script@v6
        if: contains(github.event.comment.body, '--test=')
        with:
          script: |
            console
            console.log("--- current comment ---")
            const comment = "${{ github.event.comment.body }}"
            console.log(comment)

            const test_name = comment.split('--test=')[1]

            if(test_name) {
              console.log("--- set test_name ---")
              console.log(test_name)
            }

            comment2 = "${{ github.event.comment.body }}".split('--test=')[1]
            console.log(comment2)
