name: pr-approved

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  approved:
    if: ${{ startsWith(github.event.comment.body, '/e2e') || github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    env: 
      E2E_BRANCH: main
    steps:
      - run: echo ${{ github.event.issue.number }}
      - run: echo ${{ github.event.pull_request.number }}
      - run: echo ${{ github.event.issue.number || github.event.pull_request.number }}
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.issue)

      - uses: actions/github-script@v6
        with:
          script: |
            console
            console.log("--- current comment ---")
            const comment = await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.issue.number,
            })
            console.log(comment)

            const test_name = changingBranchComment.body.split('--test=')[1]

            if(test_name) {
              console.log("--- set test_name ---")
              console.log(test_name)
            }
