name: pr-approved

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: get-reviews
        with:
          script: |
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            return reviews
      - name: Get result
        run: echo "${{ steps.get-reviews.outputs.result }}"